class APIKeyError(Exception): ...


class InvalidKeyError(APIKeyError): ...


class RevokedKeyError(APIKeyError): ...


class QuotaError(APIKeyError): ...


class InsufficientScopeError(APIKeyError): ...
