"""add_usage_tracking_rate_limit_counters_unique_constraints

Revision ID: 1eea444954e4
Revises: a3f1d8e92c47
Create Date: 2026-06-03 02:13:05.646364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1eea444954e4'
down_revision: Union[str, None] = 'a3f1d8e92c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_counters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key_id', sa.Uuid(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window', sa.String(length=16), nullable=False),
    sa.Column('count', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_id', 'window_start', 'window')
    )
    op.create_index('ix_rlc_key_id', 'rate_limit_counters', ['key_id'], unique=False)
    op.create_index('ix_rlc_window_start', 'rate_limit_counters', ['window_start'], unique=False)
    op.add_column('api_keys', sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('api_keys', sa.Column('use_count', sa.Integer(), server_default='0', nullable=False))
    op.create_unique_constraint(None, 'organizations', ['name'])
    op.create_unique_constraint(None, 'products', ['org_id', 'name'])
    op.create_unique_constraint(None, 'projects', ['org_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_column('api_keys', 'use_count')
    op.drop_column('api_keys', 'last_used_at')
    op.drop_index('ix_rlc_window_start', table_name='rate_limit_counters')
    op.drop_index('ix_rlc_key_id', table_name='rate_limit_counters')
    op.drop_table('rate_limit_counters')
    # ### end Alembic commands ###
